### PR TITLE
make this compile

### PR DESCRIPTION
**Pull request by fobser**

### CODE REVIEW

**Comment by krwesterback** [comment]
I'm not sure how, but this change was already in my tree. I suspect I'm confused about git and github. :-). Hmm. Maybe I'm on a different branch. First time I'm trying to comment on a pull request. Fascinated to see if it works. :-)

**Comment by fobser** [comment]
It does indeed work. :)

**Comment by krwesterback** [comment]
On Fri, 3 Mar 2017 at 12:30 Florian Obser <notifications@github.com> wrote:

> It does indeed work. :)
>

Good news! :-)

Of course I can't find the discussion on GitHub. :-(

Anyway, if that was a pull request for a patch needed to make 'master'
compile I'd be happy to accept it . Do you have to resubmit or is there a
button I can push in Github?

.... Ken

**Comment by fobser** [comment]
There should be a button to push.
But it's not really important for me. The diff
is trivial, you can fix it yourself, no need to
accept the pull request

**Comment by krwesterback** [comment]
Sent from my iPhone

> On Mar 5, 2017, at 1:17 PM, Florian Obser <notifications@github.com> wrote:
> 
> There should be a button to push.
> But it's not really important for me. The diff
> is trivial, you can fix it yourself, no need to
> accept the pull request

Which I have done. Thanks. Now waiting for the next pull request to see if I can handle it better. :-)

.... Ken

**Pull request closed without merging**
